-- begin SPEEDYPIZZA_ORDER
alter table SPEEDYPIZZA_ORDER add constraint FK_SPEEDYPIZZA_ORDER_ON_CUSTOMER foreign key (CUSTOMER_ID) references SPEEDYPIZZA_CUSTOMER(ID)^
create unique index IDX_SPEEDYPIZZA_ORDER_UNIQ_NUMBER_ on SPEEDYPIZZA_ORDER (NUMBER_) ^
create index IDX_SPEEDYPIZZA_ORDER_ON_CUSTOMER on SPEEDYPIZZA_ORDER (CUSTOMER_ID)^
-- end SPEEDYPIZZA_ORDER
-- begin SPEEDYPIZZA_CUSTOMER
alter table SPEEDYPIZZA_CUSTOMER add constraint FK_SPEEDYPIZZA_CUSTOMER_ON_USERNAME foreign key (USERNAME_ID) references SEC_USER(ID)^
create unique index IDX_SPEEDYPIZZA_CUSTOMER_UNIQ_USERNAME_ID on SPEEDYPIZZA_CUSTOMER (USERNAME_ID) ^
create index IDX_SPEEDYPIZZA_CUSTOMER_ON_USERNAME on SPEEDYPIZZA_CUSTOMER (USERNAME_ID)^
-- end SPEEDYPIZZA_CUSTOMER
-- begin SPEEDYPIZZA_DISH
alter table SPEEDYPIZZA_DISH add constraint FK_SPEEDYPIZZA_DISH_ON_PHOTO foreign key (PHOTO_ID) references SYS_FILE(ID)^
alter table SPEEDYPIZZA_DISH add constraint FK_SPEEDYPIZZA_DISH_ON_DISH_TYPE foreign key (DISH_TYPE_ID) references SPEEDYPIZZA_DISH_TYPE(ID)^
alter table SPEEDYPIZZA_DISH add constraint FK_SPEEDYPIZZA_DISH_ON_ORDER foreign key (ORDER_ID) references SPEEDYPIZZA_ORDER(ID)^
create unique index IDX_SPEEDYPIZZA_DISH_UNIQ_NAME on SPEEDYPIZZA_DISH (NAME) ^
create index IDX_SPEEDYPIZZA_DISH_ON_PHOTO on SPEEDYPIZZA_DISH (PHOTO_ID)^
create index IDX_SPEEDYPIZZA_DISH_ON_DISH_TYPE on SPEEDYPIZZA_DISH (DISH_TYPE_ID)^
create index IDX_SPEEDYPIZZA_DISH_ON_ORDER on SPEEDYPIZZA_DISH (ORDER_ID)^
-- end SPEEDYPIZZA_DISH
-- begin SPEEDYPIZZA_CLERK
alter table SPEEDYPIZZA_CLERK add constraint FK_SPEEDYPIZZA_CLERK_ON_USERNAME foreign key (USERNAME_ID) references SEC_USER(ID)^
create unique index IDX_SPEEDYPIZZA_CLERK_UNIQ_USERNAME_ID on SPEEDYPIZZA_CLERK (USERNAME_ID) ^
create index IDX_SPEEDYPIZZA_CLERK_ON_USERNAME on SPEEDYPIZZA_CLERK (USERNAME_ID)^
-- end SPEEDYPIZZA_CLERK
